spring:
  application:
    name: miniaturas
  datasource:
    url: jdbc:h2:mem:miniaturas
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true